async page => {
  const cdp = await page.context().newCDPSession(page);
  await cdp.send('Emulation.setDeviceMetricsOverride', { width: 1512, height: 949, deviceScaleFactor: 2, mobile: false });
  await page.emulateMedia({ colorScheme: 'dark' });
  await page.getByRole('button', { name: 'Continue', exact: true }).click({ timeout: 15000 });
  await page.getByRole('button', { name: 'Configure later', exact: true }).click({ timeout: 15000 });
  await page.getByRole('button', { name: 'TockTutor', exact: true }).click();
  await page.getByRole('button', { name: 'Notes/中文 #Open.md', exact: true }).click({ timeout: 15000 });
  const source = page.locator('[data-pane-id]').first();
  const sourceId = await source.getAttribute('data-pane-id');
  await source.getByRole('button', { name: 'More Note Actions', exact: true }).click();
  await page.getByRole('menuitemradio', { name: 'Source Mode', exact: true }).click();
  const editor = source.locator('.cm-content'); await editor.waitFor();
  await editor.fill('# Default App Proof\n\nSaved before external dispatch 🙂.\n');
  await source.getByRole('button', { name: 'More Note Actions', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Open in Default App', exact: true }).waitFor();
  await page.screenshot({ path: '/tmp/tocktutor-default-app-20260921/menu.png', scale: 'device' });
  await page.getByRole('menuitem', { name: 'Open in Default App', exact: true }).click();
  await page.getByText('Opened in the default app.', { exact: true }).first().waitFor();
  const firstStatus = await source.innerText();
  await source.getByRole('button', { name: 'More Note Actions', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Split Right', exact: true }).click();
  await page.waitForFunction(() => document.querySelectorAll('[data-pane-id]').length === 2);
  const other = page.locator(`[data-pane-id]:not([data-pane-id="${sourceId}"])`);
  await page.getByRole('button', { name: 'Notes/Other.md', exact: true }).click();
  await other.getByRole('button', { name: 'More Note Actions', exact: true }).click();
  await page.getByRole('menuitemradio', { name: 'Source Mode', exact: true }).click();
  await other.locator('.cm-content').waitFor();
  await other.locator('.cm-content').fill('# Other\n\nSeparate unsaved draft; must stay off disk.\n');
  await editor.click();
  await source.getByRole('button', { name: 'More Note Actions', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Open in Default App', exact: true }).click();
  await page.getByText('Opened in the default app.', { exact: true }).first().waitFor();
  const session = await page.evaluate(() => JSON.parse(Object.entries(localStorage).find(([key]) => key.startsWith('tocktutor.workbench'))[1]).session);
  const otherTab = session.groups.flatMap(group => group.tabs).find(tab => tab.path === 'Notes/Other.md');
  if (!otherTab?.dirty) throw new Error('Unrelated draft lost its dirty state');
  const geometry = await page.evaluate(() => ({ width: innerWidth, height: innerHeight, dpr: devicePixelRatio, theme: document.documentElement.style.colorScheme, skin: document.documentElement.dataset.tockteamSkin ?? null }));
  if (JSON.stringify(geometry) !== JSON.stringify({ width: 1512, height: 949, dpr: 2, theme: 'dark', skin: null })) throw new Error('Wrong canonical geometry/theme');
  await page.screenshot({ path: '/tmp/tocktutor-default-app-20260921/owner-only-save.png', scale: 'device' });
  await page.evaluate(id => { window.__defaultAppProof = { sourceId: id }; }, sourceId);
  return { sourceId, firstStatus, source: await source.innerText(), other: await other.innerText(), session, geometry, route: page.url(), boundary: 'OS association intercepted; no external app opened' };
}
