export const TOCKBOT_BASE_EVALUATOR_PROVENANCE = Object.freeze({
  repository: 'https://github.com/taowang1993/tockbot',
  revision: 'af214b2d1a5df8ca23bf99fad9f0408a07c2e4ba',
  sourceFiles: Object.freeze([
    'apps/web/src/components/notes/NotesBaseFilterTree.ts',
    'apps/web/src/components/notes/NotesBaseFormula.ts',
    'apps/web/src/components/notes/NotesBaseFormulaArithmetic.ts',
    'apps/web/src/components/notes/NotesBaseFormulaHtml.ts',
    'apps/web/src/components/notes/NotesBaseFormulaIcon.ts',
    'apps/web/src/components/notes/NotesBaseFormulaImage.ts',
    'apps/web/src/components/notes/NotesBaseFormulaLink.ts',
    'apps/web/src/components/notes/NotesBaseFormulaObject.ts',
    'apps/web/src/components/notes/NotesBaseFormulaPath.ts',
    'apps/web/src/components/notes/NotesBaseFormulaRegex.ts',
    'apps/web/src/components/notes/NotesBaseFormulaSyntax.ts',
    'apps/web/src/components/notes/NotesBaseFormulaTags.ts',
    'apps/web/src/components/notes/NotesBaseFormulaValue.ts',
    'apps/web/src/components/notes/NotesBaseSummaryUnique.ts',
    'apps/web/src/components/notes/NotesMediaEmbeds.ts',
    'apps/web/src/components/notes/NotesTemplates.ts',
    'apps/web/src/lib/notes-tags.ts',
  ]),
  adaptations: Object.freeze([
    'Use NodeNext .ts import extensions.',
    'Replace Convex-only Value annotations with unknown without changing runtime behavior.',
    'Extract only the pure date, image-extension, and nested-tag helpers from broader Tockbot modules.',
    'Evaluate every supported conjunction child so a later unsupported filter still fails closed.',
  ]),
})
