import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { test } from 'node:test'

const main = readFileSync(new URL('../src/main.ts', import.meta.url), 'utf8')
const client = readFileSync(new URL('../src/client.ts', import.meta.url), 'utf8')
const security = readFileSync(new URL('../src/launcher-security.ts', import.meta.url), 'utf8')
const preload = readFileSync(new URL('../src/preload.ts', import.meta.url), 'utf8')
const contracts = readFileSync(new URL('../src/contracts.ts', import.meta.url), 'utf8')
const sidebar = readFileSync(new URL('../plugins/sidebar/src/client/plugin.tsx', import.meta.url), 'utf8')
const launcherFallback = readFileSync(new URL('../plugins/sidebar/src/client/desktop-launcher-fallback.tsx', import.meta.url), 'utf8')
const i18n = readFileSync(new URL('../plugins/sidebar/src/client/i18n.ts', import.meta.url), 'utf8')
const tockTutorRoute = readFileSync(new URL('../plugins/tocktutor/packages/tockteam-tocktutor-workbench/src/route.tsx', import.meta.url), 'utf8')
const webPatch = readFileSync(new URL('../web/cordis.patch.yml', import.meta.url), 'utf8')
const tuiPatch = readFileSync(new URL('../plugins/tui/cordis.patch.yml', import.meta.url), 'utf8')

test('main assembles one launcher owner without branching the DSH workbench factory', () => {
  assert.match(main, /globalShortcut/u)
  assert.match(main, /session\.fromPartition\(LAUNCHER_SESSION_PARTITION\)/u)
  assert.match(security, /persist:tockteam-launcher/u)
  assert.match(main, /alwaysOnTop: true/u)
  assert.match(main, /frame: false/u)
  assert.match(main, /show: false/u)
  assert.match(main, /skipTaskbar: true/u)
  assert.match(main, /width: 750/u)
  assert.match(main, /height: 475/u)
  assert.match(main, /transparent: true, type: 'panel'/u)
  assert.match(main, /setWindowOpenHandler\(\(\) => \(\{ action: 'deny' \}\)\)/u)
  assert.match(main, /will-attach-webview/u)
  assert.match(main, /will-redirect/u)
  assert.match(main, /launcherController\?\.destroyWindow\(\)/u)
  assert.match(main, /launcherController\?\.dispose\(\)/u)
  assert.match(main, /executeTockTeamDestination\(record, \(\) =>/u)
  assert.match(main, /fileSearch\.executeAction\(record\)[\s\S]+network\.executeAction\(record\)[\s\S]+executeTockTeamDestination/u)
  assert.match(main, /if \(await network\.executeAction\(record\)\) \{[\s\S]+hideAfterInvocation/u)
  assert.match(main, /createLauncherLocalExtensions/u)
  assert.match(main, /local\.loadIndexedItems\(\)/u)
  assert.match(main, /local\.searchInstant\(searchTerm\)/u)
  assert.match(main, /local\.executeAction\(record\)/u)
  assert.match(main, /searchInstant: async searchTerm => \{[\s\S]+fileResults\.lastError[\s\S]+lastError: fileResults\.lastError/u)
  assert.match(main, /launcherCoreFlush = async \(\) => \{[\s\S]+await fileSearch\.close\(\)[\s\S]+await coreSearch\.close\(\)[\s\S]+await networkClose/u)
  assert.match(main, /updateSetting: async \(key, value\) => await runLauncherSettingsOperation\([\s\S]+const needsRescan = key === 'extensions\.enabledExtensionIds'[\s\S]+actions\.clear\(\)[\s\S]+fileSearch\.invalidate\(\)[\s\S]+try \{[\s\S]+requireLauncherPersistence\(\)\.updateSetting\(key, value\)[\s\S]+catch \(reason\) \{[\s\S]+actions\.clear\(\)[\s\S]+fileSearch\.invalidate\(\)[\s\S]+await launcherRescan\?\.\(\)[\s\S]+throw reason/u)
  assert.match(main, /persistSettings: async values => await runLauncherSettingsOperation\([\s\S]+repository\.updateSettings\(values\)[\s\S]+\{ mutation: true \}/u)
  assert.match(main, /resetSettings:[\s\S]+actions\.clear\(\)[\s\S]+resetLauncherSettings/u)
  assert.match(main, /runtimeUrl === undefined\) return false/u)
  assert.match(main, /createLauncherWorkbenchRouteDelivery/u)
  assert.match(main, /workbenchRouteDelivery\.markUnready/u)
  assert.match(main, /currentWorkbenchDestination: TockTeamDestination|let currentWorkbenchDestination: TockTeamDestination = 'tockcoder'/u)
  assert.match(main, /function invalidateWorkbenchReadiness[\s\S]+queueCurrentWorkbenchRoute/u)
  assert.match(main, /sender !== mainWindow\?\.webContents[\s\S]+markWorkbenchReady/u)
  assert.match(main, /workbenchReadyGeneration !== workbenchGeneration/u)
  assert.match(main, /render-process-gone[\s\S]+recoverWorkbenchRenderer/u)
  assert.match(main, /function replaceWorkbenchAfterRendererFailure[\s\S]+assignMainWindow\(createWindow\(\)\)/u)
  assert.match(main, /RuntimeStartGate|runtimeStartGate\.start/u)
  assert.match(main, /async function prepareUpdaterInstall[\s\S]+transitioning = true[\s\S]+stopRuntimeAndChannels/u)
  assert.match(main, /async function recoverUpdaterInstall[\s\S]+launcherUpdaterRuntimeWasActive = false[\s\S]+startRuntime/u)
  assert.match(main, /runtimeStartGate\.invalidate\(\)[\s\S]+invalidateWorkbenchReadiness/u)
  assert.match(main, /async function startRuntimeOwned[\s\S]+if \(runtime !== undefined \|\| runtimeUrl !== undefined\) return/u)
  assert.match(main, /startChannel[\s\S]+ensureCurrent\(\)/u)
  assert.match(main, /runtimeStartGate\.close\(\)/u)
  assert.match(sidebar, /syncWorkbenchDestination/u)
  assert.match(main, /createDesktopAppUpdater/u)
  assert.match(main, /new SingleOwnedTray/u)
  assert.match(main, /requestSecureQuit/u)
  assert.match(main, /showLauncher: 'Show TockLauncher'/u)
  assert.match(main, /text\.showLauncher[\s\S]+launcherLifecycle\?\.invokeCommand\('show'\)/u)
  assert.match(main, /flushQueuedProtocols[\s\S]+publishProtocol\(pending\[index\]!\)[\s\S]+queuedProtocolUrls\.push/u)
  assert.match(main, /if \(toggle\)[\s\S]+flushQueuedOpenRequests\(\)[\s\S]+return/u)
  assert.match(main, /async function startLiveForMarketplace\(\)[\s\S]+if \(quitting\) return/u)
  assert.match(main, /handleUnexpectedRuntimeExit/u)
  assert.match(main, /stopLiveRuntimeForMarketplace/u)
  assert.match(client, /unsubscribeTheme\(\)[\s\S]+unsubscribeRoute\(\)[\s\S]+unsubscribeCommand\(\)/u)
  assert.match(client, /deferSettingsOpen\([\s\S]+requestAnimationFrame[\s\S]+queueMicrotask/u)
  assert.doesNotMatch(main, /createWindow\([^)]*launcher/u)
})

test('workbench bridge and Desktop titlebar expose only finite launcher operations', () => {
  assert.match(contracts, /launcher: DesktopLauncherBridge/u)
  assert.match(contracts, /getState\(\): Promise<DesktopLauncherState>/u)
  assert.match(contracts, /show\(\): Promise<DesktopLauncherState>/u)
  assert.match(preload, /LAUNCHER_WINDOW_IPC_CHANNELS\.getState/u)
  assert.match(preload, /LAUNCHER_WINDOW_IPC_CHANNELS\.show/u)
  assert.match(sidebar, /DesktopLauncherFallback/u)
  assert.match(launcherFallback, /window\.dshDesktop\?\.launcher/u)
  assert.match(launcherFallback, /bridge\.getState\(\)/u)
  assert.match(launcherFallback, /bridge\.show\(\)/u)
  assert.match(launcherFallback, /Shortcut Unavailable|launcher\.shortcut-unavailable/u)
  assert.ok(launcherFallback.includes('aria-label={accessibleLabel}'))
  assert.match(tockTutorRoute, /aria-label="Open TockLauncher"/u)
  assert.match(tockTutorRoute, /launcher\.show\(\)/u)
  assert.ok(launcherFallback.includes("[body:has([data-sidebar-collapsed])_&]:!w-9"))
  assert.match(i18n, /'launcher\.button'/u)
  assert.match(i18n, /'launcher\.shortcut-unavailable'/u)
  assert.doesNotMatch(sidebar, /inject[^\n]*desktopShell/u)
})

test('Web and TUI patch layers do not receive launcher authority', () => {
  assert.doesNotMatch(webPatch, /launcher-window|tockteamLauncher|globalShortcut/u)
  assert.doesNotMatch(tuiPatch, /launcher-window|tockteamLauncher|globalShortcut/u)
})
