async page => {
  const errors = []
  page.on('pageerror', error => errors.push(String(error)))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  const cdp = await page.context().newCDPSession(page)
  await cdp.send('Emulation.setDeviceMetricsOverride', { width: 1512, height: 949, deviceScaleFactor: 2, mobile: false })
  const click = name => page.getByRole('button', { name, exact: true }).click()
  const grid = page.getByRole('grid', { name: 'Projects Results' })
  await grid.waitFor()
  if (await grid.getByRole('row').count() !== 2) throw new Error('Expected exactly one folder-filtered note')
  await grid.getByRole('gridcell', { name: 'Projects.base', exact: true }).waitFor()
  await click('Sort')
  await click('Apply Sort')
  await page.keyboard.press('Escape')
  await click('Base View')
  await page.getByRole('option', { name: 'Projects', exact: true }).click()
  const name = page.getByRole('textbox', { name: 'View Name', exact: true })
  await name.fill('Reviewed')
  await name.press('Enter')
  await page.getByRole('grid', { name: 'Reviewed Results' }).waitFor()
  await click('Close Configure View')
  const cell = page.getByRole('textbox', { name: 'Edit note.status for Projects/Review.md', exact: true })
  await cell.fill('verified')
  await cell.press('Tab')
  await page.waitForFunction(() => {
    const input = document.querySelector('input[aria-label="Edit note.status for Projects/Review.md"]')
    return input && !input.disabled && input.value === 'verified'
  })
  await click('Search')
  const search = page.getByRole('searchbox', { name: 'Find in Base', exact: true })
  await search.fill('missing')
  await page.getByText('No notes match this search.', { exact: true }).waitFor()
  await search.press('Escape')
  await page.getByRole('grid', { name: 'Reviewed Results' }).waitFor()
  if (await page.getByRole('alert').count()) throw new Error('Unexpected alert')
  const geometry = await page.evaluate(() => ({ width: innerWidth, height: innerHeight, scale: devicePixelRatio, colorScheme: document.documentElement.style.colorScheme, htmlSkin: document.documentElement.dataset.tockteamSkin ?? null, bodySkin: document.body.dataset.tockteamSkin ?? null, route: location.pathname }))
  if (geometry.width !== 1512 || geometry.height !== 949 || geometry.scale !== 2 || geometry.colorScheme !== 'dark' || geometry.htmlSkin !== null || geometry.bodySkin !== null) throw new Error(JSON.stringify(geometry))
  if (errors.length) throw new Error(JSON.stringify(errors))
  await page.screenshot({ path: '/tmp/tocktutor-base-review/verified-dark.png', scale: 'device' })
  return { geometry, errors, rows: await page.getByRole('grid', { name: 'Reviewed Results' }).getByRole('row').allTextContents(), checks: ['this.file folder filter and owner name', 'source authoring without final newline', 'sort and rename saved', 'cell edit saved', 'search and Escape restored results'] }
}
