// Owned, isolated production Desktop verification. Launch only via extended_display.
const { app, clipboard, shell } = require('electron');
const fs = require('node:fs'); const path = require('node:path'); const { pathToFileURL } = require('node:url');
const repo='/Users/taowang/projects/worktrees/tutor';
if(!app.commandLine.hasSwitch('use-mock-keychain')) throw Error('Mock Keychain required');
const root=app.getPath('appData'), data=app.getPath('userData'), vault=path.join(root,'Merge Proof Vault');
const put=(file,value)=>{fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,typeof value==='string'?value:JSON.stringify(value,null,2));};
put(path.join(vault,'Notes/Source.md'),'---\nstatus: source\n---\n# Source\n\nSource paragraph 🙂.\n');
put(path.join(vault,'Notes/Destination.md'),'---\nstatus: destination\n---\n# Destination\n\nDestination paragraph.\n');
put(path.join(vault,'Referrer.md'),'[[Notes/Source]]\n');
put(path.join(vault,'Other.md'),'# Other\n\nAn unrelated note.\n');
put(path.join(data,'skins.json'),{activeId:null,fallbackTheme:'dark'});
put(path.join(data,'tocktutor/vault-state/selection.json'),{activeRoot:vault,recents:[]});
app.commandLine.appendSwitch('user-data-dir',data); app.setAppPath(repo);
process.argv=[process.execPath,repo,'--use-mock-keychain'];
process.env.TOCKTEAM_RESOURCES_ROOT=path.join(repo,'.stage');process.env.TOCKTEAM_SOURCE_ROOT=repo;process.env.TOCKTEAM_TRUSTED_RAYCAST_DENY_EFFECTS_PROOF='1';
for(const key of Object.keys(process.env)) if(/TOKEN|API_KEY|SECRET/.test(key)) delete process.env[key];
clipboard.writeText=(text,type)=>fs.appendFileSync(path.join(root,'clipboard.jsonl'),JSON.stringify({text,type})+'\n');
shell.openPath=async target=>{if(!target.startsWith(fs.realpathSync(vault)+path.sep))throw Error('Unexpected target');fs.appendFileSync(path.join(root,'open-path.jsonl'),JSON.stringify({target,content:fs.readFileSync(target,'utf8')})+'\n');return '';};
put(path.join(root,'fixture.json'),{root,data,vault,boundary:'Real Desktop, Workbench, Host and Runtime. OS association and clipboard intercepted.'});
import(pathToFileURL(path.join(repo,'dist/main.js')).href).catch(error=>{console.error(error);app.exit(1);});
