const { app } = require('electron')
const { mkdirSync, writeFileSync } = require('node:fs')
const { join } = require('node:path')
app.commandLine.appendSwitch('use-mock-keychain')
const root = '/tmp/tocktutor-base-followup'
const data = join(app.getPath('appData'), 'TockTeam-Desktop-Dev')
mkdirSync(join(data, 'tocktutor', 'vault-state'), { recursive: true })
writeFileSync(join(data, 'skins.json'), JSON.stringify({ activeId: null, fallbackTheme: 'dark' }))
writeFileSync(join(data, 'tocktutor', 'vault-state', 'selection.json'), JSON.stringify({ activeRoot: join(root, 'vault'), recents: [] }))
for (const name of ['Alpha', 'Beta']) writeFileSync(join(root, 'vault', `${name}.md`), `---\nscore: ${'9'.repeat(308)}\n---\n# ${name}\n`)
writeFileSync(join(root, 'vault', 'Review.base'), 'views:\n  - name: Commented\n    filters:\n# This comment must not discard the filter\n      and:\n        - false\n  - name: Summary\n    order: [file.name]\n    summaries: [sum(note.score)]\n')
writeFileSync(join(root, 'vault', 'Guarded.base'), 'filters:\n# This comment must not discard the filter\n  and:\n    - false\nviews:\n  - name: Guarded\n')
writeFileSync(join(root, 'vault', 'Invalid.base'), 'filters: true\n  and:\n    - false\nviews:\n  - name: Invalid\n')
process.chdir('/Users/taowang/projects/tockteam')
void import('file:///Users/taowang/projects/tockteam/dist/main.js')
