async page => {
  const errors = []
  page.on('pageerror', error => errors.push(String(error)))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  const cdp = await page.context().newCDPSession(page)
  await cdp.send('Emulation.setDeviceMetricsOverride', { width: 1512, height: 949, deviceScaleFactor: 2, mobile: false })
  const click = name => page.getByRole('button', { name, exact: true }).click()
  await click('Guarded.base')
  await page.getByText('No notes match this view.', { exact: true }).waitFor()
  await page.getByRole('button', { name: '0 Results', exact: true }).waitFor()
  await click('Invalid.base')
  await page.getByRole('alert').filter({ hasText: 'Base scalar filter contains unsupported nested syntax.' }).waitFor()
  await click('Review.base')
  await page.getByText('No notes match this view.', { exact: true }).waitFor()
  await click('Base View')
  await page.getByRole('option', { name: 'Summary', exact: true }).click()
  await page.getByRole('alert').filter({ hasText: 'Unsupported Base expression: sum(note.score)' }).waitFor()
  await click('Search')
  const search = page.getByRole('searchbox', { name: 'Find in Base', exact: true })
  await search.fill('Alpha')
  const grid = page.getByRole('grid', { name: 'Summary Results', exact: true })
  await grid.waitFor()
  if (await grid.getByRole('row').count() !== 2) throw new Error('Expected only Alpha after searching')
  await grid.getByRole('gridcell', { name: 'Alpha', exact: true }).waitFor()
  await page.getByText(String(Number('9'.repeat(308))), { exact: true }).waitFor()
  if (await page.getByRole('alert').count()) throw new Error('Search retained hidden-row summary error')
  const geometry = await page.evaluate(() => ({ width: innerWidth, height: innerHeight, scale: devicePixelRatio, colorScheme: document.documentElement.style.colorScheme, htmlSkin: document.documentElement.dataset.tockteamSkin ?? null, bodySkin: document.body.dataset.tockteamSkin ?? null, route: location.pathname + location.search }))
  if (geometry.width !== 1512 || geometry.height !== 949 || geometry.scale !== 2 || geometry.colorScheme !== 'dark' || geometry.htmlSkin !== null || geometry.bodySkin !== null) throw new Error(JSON.stringify(geometry))
  if (errors.length) throw new Error(JSON.stringify(errors))
  await page.screenshot({ path: '/tmp/tocktutor-base-followup/verified-dark.png', scale: 'device' })
  await search.fill('Missing')
  await page.getByText('No notes match this search.', { exact: true }).waitFor()
  if (await page.getByRole('alert').count()) throw new Error('Empty search retained hidden-row summary error')
  await search.press('Escape')
  await page.getByRole('alert').filter({ hasText: 'Unsupported Base expression: sum(note.score)' }).waitFor()
  return { geometry, errors, mode: 'Base Table', checks: ['global filter survives unindented comment', 'malformed scalar filter is unavailable', 'view filter survives unindented comment', 'overflow summary correctly fails without search', 'search shows Alpha and its finite summary', 'empty search results have no summary error', 'Escape restores unfiltered summary error'] }
}
