async page => {
 const evidence='/tmp/tockteam-raycast-scope.5lIcfC/form-desktop';
 const pages=page.context().pages();const candidates=[];for(const p of pages)if(await p.title()==='TockLauncher'&&p.url()==='file:///Users/taowang/projects/tockteam/dist/launcher.html')candidates.push(p);if(candidates.length!==1)throw Error('Expected one exact owned launcher');page=candidates[0];
 const errors=[],consoleErrors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});page.on('request',r=>{if(!/^(file:|data:|http:\/\/127\.0\.0\.1:)/.test(r.url()))requests.push(new URL(r.url()).origin)});
 const cdp=await page.context().newCDPSession(page);await cdp.send('Emulation.setDeviceMetricsOverride',{width:1512,height:949,deviceScaleFactor:2,mobile:false});await page.emulateMedia({colorScheme:'light',reducedMotion:'reduce'});
 if(await page.getByRole('button',{name:'Back to Search',exact:true}).isVisible())await page.getByRole('button',{name:'Back to Search',exact:true}).click();
 await page.getByRole('button',{name:'Manage Local Raycast Extensions',exact:true}).click();
 await page.evaluate(()=>{window.__formProofUnsubscribe?.();window.__formProofSaved=null;window.__formProofUnsubscribe=window.tockteamLauncher.onUserRaycastView(message=>{const walk=node=>{if(!node||typeof node==='string')return;if(node.type==='raycast-list-item'&&node.props.title==='Saved Fake Entry')window.__formProofSaved=JSON.parse(node.props.subtitle);for(const child of node.children??[])walk(child)};walk(message.root)})});
 await page.locator('[data-user-raycast-action="open"]').click();
 const name=page.getByRole('textbox',{name:'Name',exact:true});await name.waitFor();const password=page.getByLabel('Password',{exact:true}),notes=page.getByRole('textbox',{name:'Notes',exact:true}),check=page.getByRole('checkbox',{name:'Include a Summary',exact:true});
 const facts=async()=>page.evaluate(()=>({geometry:[innerWidth,innerHeight,devicePixelRatio],url:location.href,mode:document.documentElement.style.colorScheme,skin:document.body.dataset.tockteamSkin??document.documentElement.dataset.tockteamSkin??null,nativeIsolation:typeof require==='undefined'&&typeof process==='undefined',formCount:document.forms.length}));
 const capture=async(file,state)=>{const f=await facts();if(JSON.stringify(f.geometry)!=='[1512,949,2]'||f.mode!=='dark'||f.skin!==null||!f.nativeIsolation)throw Error('Wrong canonical geometry/theme/isolation '+JSON.stringify(f));await page.screenshot({path:evidence+'/'+file});return{file,state,...f}};
 await name.focus();await page.waitForTimeout(200);
 const backpressure=await name.evaluate(input=>{let accepted=0;for(let index=0;index<100&&!input.disabled;index++){input.value='Draft '+index;input.dispatchEvent(new Event('input',{bubbles:true}));accepted++}return{accepted,disabled:input.disabled,lastDraft:input.value}});
 if(backpressure.accepted!==32||!backpressure.disabled||backpressure.lastDraft!=='Draft 31')throw Error('Unbounded native edit backlog '+JSON.stringify(backpressure));
 await page.getByRole('button',{name:'Reset Name',exact:true}).click();await page.waitForFunction(()=>{const n=document.querySelector('input[aria-label="Name"]');return !n.disabled&&n.value==='First'});
 const captures=[];captures.push(await capture('basic-form-dark.png','Basic native text/password/textarea/checkbox defaults in the real TockLauncher, dark app/light system, no skin'));
 const widths=await page.locator('form :is(input,textarea)').evaluateAll(nodes=>nodes.map(n=>({name:n.getAttribute('aria-label'),type:n.type,box:getComputedStyle(n).boxSizing,width:n.getBoundingClientRect().width,parentWidth:n.parentElement.getBoundingClientRect().width})));if(widths.some(f=>f.width>f.parentWidth+1))throw Error('Field overflow '+JSON.stringify(widths));
 if(await password.getAttribute('type')!=='password'||await notes.inputValue()!=='First line\nSecond line'||await check.isChecked())throw Error('Wrong native defaults');
 await name.fill('');await page.getByRole('button',{name:'Save Fake Entry',exact:true}).click();await page.getByText('Enter a name.',{exact:true}).waitFor();await page.waitForFunction(()=>!document.querySelector('input[aria-label="Name"]').disabled);if(await name.getAttribute('aria-invalid')!=='true')throw Error('Error association missing');captures.push(await capture('basic-form-error-dark.png','Rejected empty-name submit, accessible inline error, other drafts preserved'));
 await name.fill('Changed');await page.getByRole('button',{name:'Reset Name',exact:true}).click();await page.waitForFunction(()=>{const n=document.querySelector('input[aria-label="Name"]');return !n.disabled&&n.value==='First'&&document.activeElement===n});
 await notes.fill('Reviewed\nOffline Notes');await password.fill('fake-edited');await check.check();await name.fill('Ada');await page.waitForTimeout(200);await name.focus();await name.press('End');
 const visible=await page.locator('form').evaluate(form=>({text:form.textContent,controls:[...form.querySelectorAll('input,textarea')].map(n=>({label:n.getAttribute('aria-label'),type:n.type,checked:n.type==='checkbox'?n.checked:null,value:n.type==='password'?'[masked fake text]':n.value})),focus:document.activeElement?.getAttribute('aria-label'),focusRing:getComputedStyle(document.activeElement).outlineStyle}));
 if(visible.controls.find(n=>n.label==='Summary'))throw Error('Checkbox accessible name must use its own label');captures.push(await capture('basic-form-edited-dark.png','Edited fake values, checked checkbox, preserved name focus and visible focus ring'));
 // Submit immediately after another delayed controlled edit. Correct saved data proves real main IPC waited for field completion.
 await name.fill('Ada Final');await notes.press('Control+Enter');await page.getByText('Saved Fake Entry',{exact:true}).waitFor();
 const result=await page.evaluate(()=>window.__formProofSaved);const saved={name:'Ada Final',password:'fake-edited',notes:'Reviewed\nOffline Notes',summary:true};if(!result||Object.keys(result).length!==4||Object.entries(saved).some(([key,value])=>result[key]!==value))throw Error('Lost an edit on keyboard submit '+JSON.stringify(result));
 captures.push(await capture('basic-form-saved-dark.png','Exact typed fake values submitted after pending edit using Control+Enter'));
 if(errors.length||consoleErrors.length||requests.length)throw Error(JSON.stringify({errors,consoleErrors,requests}));
 const proof={realDesktop:true,firstPartyOfflineFixture:true,accountOrCredentialOperations:false,rootProduct:'dist/main.js',route:'file:///Users/taowang/projects/tockteam/dist/launcher.html',canonical:'dark app/light system with reduced motion and no skin',captures,widths,visible,saved,backpressure,errors,consoleErrors,nonlocalRequests:requests,knownBootConsoleDiagnostic:'Chromium ignores frame-ancestors when delivered through an HTML meta tag; existing launcher CSP diagnostic captured separately.'};await page.evaluate(()=>window.__formProofUnsubscribe?.());return {passed:true,...proof};
}
