async page => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  const cdp = await page.context().newCDPSession(page);
  await cdp.send('Emulation.setDeviceMetricsOverride', { width: 1512, height: 949, deviceScaleFactor: 2, mobile: false });
  await page.emulateMedia({ colorScheme: 'dark', reducedMotion: 'reduce' });
  await page.getByRole('button', { name: 'Review Merge', exact: true }).click();
  const search = page.getByRole('combobox', { name: 'Merge Destination' });
  await search.fill('Dest');
  const candidates = await page.getByRole('option').allTextContents();
  if (JSON.stringify(candidates) !== JSON.stringify(['Archive/Dest.md', 'Other/Dest.markdown'])) throw new Error('Wrong destination candidates');
  await search.press('Shift+Enter');
  const placement = page.getByRole('combobox', { name: 'Placement', exact: true });
  await placement.waitFor();
  if (await placement.inputValue() !== 'prepend') throw new Error('Shift+Enter did not prepend');
  if (!await page.getByRole('button', { name: 'Preview Merge', exact: true }).isDisabled()) throw new Error('Missing property choice was accepted');
  await page.getByRole('combobox', { name: 'Value for status', exact: true }).selectOption('source');
  const geometry = await page.evaluate(() => ({ width: innerWidth, height: innerHeight, dpr: devicePixelRatio, theme: document.documentElement.style.colorScheme, skin: document.documentElement.dataset.tockteamSkin ?? null }));
  if (JSON.stringify(geometry) !== JSON.stringify({ width:1512,height:949,dpr:2,theme:'dark',skin:null })) throw new Error('Wrong geometry/theme');
  await page.screenshot({ path: '/tmp/tutor-merge-ui-proof/choices.png', scale: 'device' });
  await page.getByRole('button', { name: 'Preview Merge', exact: true }).click();
  await page.getByRole('heading', { name: 'Merge Preview', exact: true }).waitFor();
  if (!await page.getByRole('note').innerText().then(text => text.includes('Choose Keep Original'))) throw new Error('Missing unsafe retirement warning');
  const content = await page.getByLabel('Destination Content', { exact: true }).textContent();
  if (!content.includes('[Diagram](../assets/diagram.png)') || !content.startsWith('---\nstatus: draft\n---\n# Source')) throw new Error('Wrong rebased content/properties');
  await page.getByText('Other Notes to Update (1)', { exact: true }).click();
  await page.getByText('Ref.md', { exact: true }).click();
  await page.getByRole('heading', { name: 'Merge Preview', exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: '/tmp/tutor-merge-ui-proof/preview.png', scale: 'device' });
  await page.getByRole('combobox', { name: 'Original Note', exact: true }).selectOption('link');
  if (await page.getByRole('heading', { name: 'Merge Preview', exact: true }).count()) throw new Error('Decision edit retained old preview');
  await page.getByRole('button', { name: 'Preview Merge', exact: true }).click();
  await page.getByLabel('Original Note Content', { exact: true }).waitFor();
  const leftover = await page.getByLabel('Original Note Content', { exact: true }).textContent();
  if (leftover !== '[[Archive/Dest.md|Archive/Dest]]\n') throw new Error('Wrong leftover');
  await page.getByRole('combobox', { name: 'Original Note', exact: true }).selectOption('keep');
  await page.getByRole('button', { name: 'Preview Merge', exact: true }).click();
  await page.getByRole('heading', { name: 'Merge Preview', exact: true }).waitFor();
  if (await page.getByRole('note').count()) throw new Error('Keep Original still blocked');
  if (await page.getByRole('button', { name: 'Merge', exact: true }).count()) throw new Error('Read-only slice exposed apply');
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  await page.waitForFunction(() => document.activeElement?.textContent === 'Review Merge');
  await page.getByRole('button', { name: 'Review Merge', exact: true }).click();
  await page.getByRole('combobox', { name: 'Merge Destination' }).press('Escape');
  await page.waitForFunction(() => !document.querySelector('[role=dialog]'));
  await page.getByRole('button', { name: 'Review Merge', exact: true }).click();
  await page.getByRole('combobox', { name: 'Merge Destination' }).fill('Dest');
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
  await page.mouse.click(20, 20);
  await page.waitForFunction(() => !document.querySelector('[role=dialog]'));
  await cdp.send('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 2, mobile: false });
  await page.getByRole('button', { name: 'Review Merge', exact: true }).click();
  await page.getByRole('option', { name: 'Archive/Dest.md', exact: true }).click();
  await page.getByRole('combobox', { name: 'Placement', exact: true }).waitFor();
  const narrow = await page.getByRole('dialog').evaluate(element => ({ width: element.getBoundingClientRect().width, scrollWidth: element.scrollWidth, clientWidth: element.clientWidth, viewport: innerWidth }));
  if (narrow.width > narrow.viewport || narrow.scrollWidth > narrow.clientWidth) throw new Error('Narrow overflow');
  await page.evaluate(() => { document.documentElement.style.colorScheme = 'light'; document.body.removeAttribute('data-ds-dark-theme'); });
  await page.emulateMedia({ colorScheme: 'light', reducedMotion: 'reduce' });
  const light = await page.getByRole('dialog').evaluate(element => ({ color: getComputedStyle(element).color, background: getComputedStyle(element).backgroundColor }));
  if (light.color === light.background) throw new Error('Unreadable light theme');
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  if (errors.length) throw new Error(JSON.stringify(errors));
  return { geometry, candidates, content, leftover, narrow, light, errors, route: page.url(), mode: 'read-only component harness', checks: ['explicit property choice','Shift+Enter prepend','relative-link rebasing','inbound review','unsafe source warning','link leftover','keep source','decision invalidation','no apply control','Cancel and focus restoration','Escape','outside dismissal','narrow layout','light theme','reduced motion'], limitation: 'Fixture read-only transport; not production menu/apply or full Desktop acceptance' };
}
