/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _tockteam_tocktutor_assistant_tocktutorAssistant_approveProposal_parameter_0$schema = z.object({
  'proposalId': z.string(),
})
const _tockteam_tocktutor_assistant_tocktutorAssistant_approveProposal_result$schema = z.object({
  'proposalId': z.string(),
  'auditCorrelationId': z.string(),
  'operation': z.union([z.literal("create"), z.literal("update")]),
  'destination': z.string(),
  'snapshotCaptured': z.boolean(),
  'status': z.union([z.literal("created"), z.literal("saved")]),
})
const _tockteam_tocktutor_assistant_tocktutorAssistant_audit_parameter_0$schema = z.object({
  'offset': z.number().optional(),
  'limit': z.number().optional(),
})
const _tockteam_tocktutor_assistant_tocktutorAssistant_audit_result$schema = z.object({
  'entries': z.array(z.object({
  'auditId': z.string(),
  'auditCorrelationId': z.string(),
  'proposalId': z.string(),
  'timestamp': z.number(),
  'outcome': z.union([z.literal("applied"), z.literal("staged"), z.literal("approval-consumed"), z.literal("approval-denied"), z.literal("approval-failed"), z.literal("rejected")]),
  'destination': z.string(),
  'operation': z.union([z.literal("create"), z.literal("update")]),
  'contentBytes': z.number(),
  'reason': z.string().optional(),
})),
  'dropped': z.number(),
  'total': z.number(),
  'nextOffset': z.union([z.literal(null), z.number()]),
})
const _tockteam_tocktutor_assistant_tocktutorAssistant_continueTurn_context$schema = z.string()
const _tockteam_tocktutor_assistant_tocktutorAssistant_continueTurn_parameter_0$schema = z.object({
  'mode': z.union([z.literal("followup"), z.literal("inject"), z.literal("steer")]),
  'text': z.string(),
})
const _tockteam_tocktutor_assistant_tocktutorAssistant_continueTurn_result$schema = z.object({
  'status': z.literal("accepted"),
  'mode': z.union([z.literal("followup"), z.literal("inject"), z.literal("steer")]),
  'redacted': z.boolean(),
  'truncated': z.boolean(),
})
const _tockteam_tocktutor_assistant_tocktutorAssistant_currentSettings_result$schema = z.object({
  'provider': z.string(),
  'model': z.string(),
  'writePermission': z.union([z.literal("read-only"), z.literal("propose")]),
  'aiSearch': z.union([z.literal("off"), z.literal("on-demand"), z.literal("automatic")]).optional(),
})
const _tockteam_tocktutor_assistant_tocktutorAssistant_listProposals_parameter_0$schema = z.object({
  'offset': z.number().optional(),
  'limit': z.number().optional(),
})
const _tockteam_tocktutor_assistant_tocktutorAssistant_listProposals_result$schema = z.object({
  'proposals': z.array(z.object({
  'proposalId': z.string(),
  'auditCorrelationId': z.string(),
  'createdAt': z.number(),
  'expiresAt': z.number(),
  'destination': z.string(),
  'operation': z.union([z.literal("create"), z.literal("update")]),
  'contentBytes': z.number(),
  'contentChars': z.number(),
  'preview': z.string(),
  'warnings': z.array(z.string()),
  'skippedEntries': z.array(z.string()),
  'skippedEntryCount': z.number(),
})),
  'total': z.number(),
  'nextOffset': z.union([z.literal(null), z.number()]),
})
const _tockteam_tocktutor_assistant_tocktutorAssistant_rejectProposal_parameter_0$schema = z.object({
  'proposalId': z.string(),
  'reason': z.string(),
})
const _tockteam_tocktutor_assistant_tocktutorAssistant_rejectProposal_result$schema = z.object({
  'proposalId': z.string(),
  'auditCorrelationId': z.string(),
})
const _tockteam_tocktutor_assistant_tocktutorAssistant_saveSettings_parameter_0$schema = z.object({
  'provider': z.string(),
  'model': z.string(),
  'writePermission': z.union([z.literal("read-only"), z.literal("propose")]),
  'aiSearch': z.union([z.literal("off"), z.literal("on-demand"), z.literal("automatic")]).optional(),
})
const _tockteam_tocktutor_assistant_tocktutorAssistant_saveSettings_result$schema = z.object({
  'provider': z.string(),
  'model': z.string(),
  'writePermission': z.union([z.literal("read-only"), z.literal("propose")]),
  'aiSearch': z.union([z.literal("off"), z.literal("on-demand"), z.literal("automatic")]).optional(),
})
const _tockteam_tocktutor_assistant_tocktutorAssistant_searchIntelligence_parameter_0$schema = z.object({
  'query': z.string(),
  'vaultGeneration': z.number(),
  'mode': z.literal("related"),
  'directory': z.string().optional(),
  'modifiedFrom': z.number().optional(),
  'modifiedTo': z.number().optional(),
  'titleOnly': z.boolean().optional(),
})
const _tockteam_tocktutor_assistant_tocktutorAssistant_searchIntelligence_result$schema = z.object({
  'status': z.union([z.literal("applied"), z.literal("disabled"), z.literal("provider-unavailable"), z.literal("invalid-output"), z.literal("error"), z.literal("cancelled")]),
  'matches': z.array(z.object({
  'id': z.string().optional(),
  'path': z.string(),
  'kind': z.union([z.literal("base"), z.literal("block"), z.literal("canvas"), z.literal("content"), z.literal("line"), z.literal("path"), z.literal("property"), z.literal("section"), z.literal("tag"), z.literal("task")]),
  'line': z.union([z.literal(null), z.number()]),
  'preview': z.string(),
  'lineEnd': z.union([z.literal(null), z.number()]).optional(),
  'score': z.number().optional(),
  'operator': z.union([z.literal("related"), z.literal("block"), z.literal("content"), z.literal("line"), z.literal("path"), z.literal("property"), z.literal("section"), z.literal("tag"), z.literal("task"), z.literal("any"), z.literal("file"), z.literal("task-done"), z.literal("task-todo")]).optional(),
  'provenance': z.union([z.literal("canvas"), z.literal("path"), z.literal("section"), z.literal("task"), z.literal("body"), z.literal("frontmatter")]).optional(),
})),
})

export const TYPERT = {
  package: '@tockteam/tocktutor-assistant',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@tockteam/tocktutor-assistant#tocktutorAssistant/approveProposal',
      service: 'tocktutorAssistant',
      namespace: 'tocktutorAssistant',
      method: 'approveProposal',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@tockteam/tocktutor-assistant/client#AssistantApprovalRequest',
            schema: _tockteam_tocktutor_assistant_tocktutorAssistant_approveProposal_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@tockteam/tocktutor-assistant/client#AssistantApprovalView',
        schema: _tockteam_tocktutor_assistant_tocktutorAssistant_approveProposal_result$schema,
      },
      sourceLocation: {"file":"packages/assistant/src/remote-model.ts","line":57,"column":9},
    },
    {
      id: '@tockteam/tocktutor-assistant#tocktutorAssistant/audit',
      service: 'tocktutorAssistant',
      namespace: 'tocktutorAssistant',
      method: 'audit',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@tockteam/tocktutor-assistant/client#AssistantPageRequest',
            schema: _tockteam_tocktutor_assistant_tocktutorAssistant_audit_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@tockteam/tocktutor-assistant/client#AssistantAuditResult',
        schema: _tockteam_tocktutor_assistant_tocktutorAssistant_audit_result$schema,
      },
      sourceLocation: {"file":"packages/assistant/src/remote-model.ts","line":81,"column":9},
    },
    {
      id: '@tockteam/tocktutor-assistant#tocktutorAssistant/continueTurn',
      service: 'tocktutorAssistant',
      namespace: 'tocktutorAssistant',
      method: 'continueTurn',
      invocation: {
        kind: 'context',
        context: 'agent',
        wire: 'agentId',
        codec: {
          mode: 'strict',
          typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
          schema: _tockteam_tocktutor_assistant_tocktutorAssistant_continueTurn_context$schema,
        },
      },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@tockteam/tocktutor-assistant/client#AssistantTurnRequest',
            schema: _tockteam_tocktutor_assistant_tocktutorAssistant_continueTurn_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@tockteam/tocktutor-assistant/client#AssistantTurnResult',
        schema: _tockteam_tocktutor_assistant_tocktutorAssistant_continueTurn_result$schema,
      },
      sourceLocation: {"file":"packages/assistant/src/remote-model.ts","line":41,"column":9},
    },
    {
      id: '@tockteam/tocktutor-assistant#tocktutorAssistant/currentSettings',
      service: 'tocktutorAssistant',
      namespace: 'tocktutorAssistant',
      method: 'currentSettings',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@tockteam/tocktutor-assistant/client#AssistantSettingsView',
        schema: _tockteam_tocktutor_assistant_tocktutorAssistant_currentSettings_result$schema,
      },
      sourceLocation: {"file":"packages/assistant/src/remote-model.ts","line":28,"column":9},
    },
    {
      id: '@tockteam/tocktutor-assistant#tocktutorAssistant/listProposals',
      service: 'tocktutorAssistant',
      namespace: 'tocktutorAssistant',
      method: 'listProposals',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@tockteam/tocktutor-assistant/client#AssistantPageRequest',
            schema: _tockteam_tocktutor_assistant_tocktutorAssistant_listProposals_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@tockteam/tocktutor-assistant/client#AssistantProposalListResult',
        schema: _tockteam_tocktutor_assistant_tocktutorAssistant_listProposals_result$schema,
      },
      sourceLocation: {"file":"packages/assistant/src/remote-model.ts","line":49,"column":9},
    },
    {
      id: '@tockteam/tocktutor-assistant#tocktutorAssistant/rejectProposal',
      service: 'tocktutorAssistant',
      namespace: 'tocktutorAssistant',
      method: 'rejectProposal',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@tockteam/tocktutor-assistant/client#AssistantRejectionRequest',
            schema: _tockteam_tocktutor_assistant_tocktutorAssistant_rejectProposal_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@tockteam/tocktutor-assistant/client#AssistantDecisionView',
        schema: _tockteam_tocktutor_assistant_tocktutorAssistant_rejectProposal_result$schema,
      },
      sourceLocation: {"file":"packages/assistant/src/remote-model.ts","line":65,"column":9},
    },
    {
      id: '@tockteam/tocktutor-assistant#tocktutorAssistant/saveSettings',
      service: 'tocktutorAssistant',
      namespace: 'tocktutorAssistant',
      method: 'saveSettings',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@tockteam/tocktutor-assistant/client#AssistantSettingsView',
            schema: _tockteam_tocktutor_assistant_tocktutorAssistant_saveSettings_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@tockteam/tocktutor-assistant/client#AssistantSettingsView',
        schema: _tockteam_tocktutor_assistant_tocktutorAssistant_saveSettings_result$schema,
      },
      sourceLocation: {"file":"packages/assistant/src/remote-model.ts","line":33,"column":9},
    },
    {
      id: '@tockteam/tocktutor-assistant#tocktutorAssistant/searchIntelligence',
      service: 'tocktutorAssistant',
      namespace: 'tocktutorAssistant',
      method: 'searchIntelligence',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@tockteam/tocktutor-assistant/client#AssistantSearchIntelligenceRequest',
            schema: _tockteam_tocktutor_assistant_tocktutorAssistant_searchIntelligence_parameter_0$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@tockteam/tocktutor-assistant/client#AssistantSearchIntelligenceResult',
        schema: _tockteam_tocktutor_assistant_tocktutorAssistant_searchIntelligence_result$schema,
      },
      sourceLocation: {"file":"packages/assistant/src/remote-model.ts","line":73,"column":9},
    },
  ],
  model: {
    "services": [],
    "events": [],
    "objects": []
  },
}
