/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { SessionId } from '@deepseek-ai/dsh-session/types'
import type { AssistantApprovalRequest, AssistantApprovalView, AssistantAuditResult, AssistantDecisionView, AssistantPageRequest, AssistantProposalListResult, AssistantRejectionRequest, AssistantSettingsView, AssistantTurnRequest, AssistantTurnResult } from '@tockteam/tocktutor-assistant/client'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$746f636b7475746f72417373697374616e74 {
    approveProposal: (request: AssistantApprovalRequest, signal?: AbortSignal) => Promise<RemoteResult<AssistantApprovalView>>
    audit: (request: AssistantPageRequest, signal?: AbortSignal) => Promise<RemoteResult<AssistantAuditResult>>
    currentSettings: (signal?: AbortSignal) => Promise<RemoteResult<AssistantSettingsView>>
    listProposals: (request: AssistantPageRequest, signal?: AbortSignal) => Promise<RemoteResult<AssistantProposalListResult>>
    rejectProposal: (request: AssistantRejectionRequest, signal?: AbortSignal) => Promise<RemoteResult<AssistantDecisionView>>
    saveSettings: (request: AssistantSettingsView, signal?: AbortSignal) => Promise<RemoteResult<AssistantSettingsView>>
  }
  interface TypertRemoteMap {
    'tocktutorAssistant/approveProposal': (request: AssistantApprovalRequest, signal?: AbortSignal) => Promise<RemoteResult<AssistantApprovalView>>
    'tocktutorAssistant/audit': (request: AssistantPageRequest, signal?: AbortSignal) => Promise<RemoteResult<AssistantAuditResult>>
    'tocktutorAssistant/currentSettings': (signal?: AbortSignal) => Promise<RemoteResult<AssistantSettingsView>>
    'tocktutorAssistant/listProposals': (request: AssistantPageRequest, signal?: AbortSignal) => Promise<RemoteResult<AssistantProposalListResult>>
    'tocktutorAssistant/rejectProposal': (request: AssistantRejectionRequest, signal?: AbortSignal) => Promise<RemoteResult<AssistantDecisionView>>
    'tocktutorAssistant/saveSettings': (request: AssistantSettingsView, signal?: AbortSignal) => Promise<RemoteResult<AssistantSettingsView>>
  }
  interface TypertRemoteNamespaceMap {
    'tocktutorAssistant': TypertRemoteNamespace$746f636b7475746f72417373697374616e74
  }
  interface TypertRemoteScopeMap {
    'agent:tocktutorAssistant/continueTurn': (request: AssistantTurnRequest, signal?: AbortSignal) => Promise<RemoteResult<AssistantTurnResult>>
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
